<a href="https://colab.research.google.com/github/Jpsama1236/ML_algorithms/blob/main/PCA_step_by_step.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
np.random.seed(23)
mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)
df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)
df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])
df1['target'] = 0
df = pd.concat([df,df])
df = df.sample(40)

In [7]:
df

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
14  0.420623  0.411620 -0.071324       1
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
9   1.267248  0.173634 -1.223255       1
11  1.968435 -0.547788 -0.679418       1
4   0.322272  0.060343 -1.043450       1
12 -2.506230  0.146960  0.606195       1
13 -0.022539  0.013422  0.935945       1
16 -0.420844 -0.551989 -0.121098       1
18 -0.331617 -1.632386  0.619114       1
0   0.666988  0.025813 -0.777619       1
5  -1.009942  0.441736  1.128877       1
19 -0.992574 -0.161346  1.192404       1
2  -0.367548 -1.137460 -1.322148       1
8   0.241106 -0.952510 -0.136267       1
15 -0.045438  1.040886 -0.094035       1
19 -0.992574 -0.161346  1.192404       1
10  1.415320  0.457711  0.728876       1
5  -1.009942  0.441736  1.128877       1
1   0.948634  0.701672 -1.051082       1
17  0.190141  0.512137  0.131538       1
16 -0.420844 -0.551989 -0.121098       1
18 -0.331617 -1.632386  0.619114       1
7   1.045371  0.538162  0.812119       1
6  -1.838068 -0.938769 -0.201841       1
3   1.772258 -0.347459  0.670140       1
1   0.948634  0.701672 -1.051082       1
10  1.415320  0.457711  0.728876       1
0   0.666988  0.025813 -0.777619       1
8   0.241106 -0.952510 -0.136267       1
4   0.322272  0.060343 -1.043450       1
7   1.045371  0.538162  0.812119       1
6  -1.838068 -0.938769 -0.201841       1
17  0.190141  0.512137  0.131538       1
13 -0.022539  0.013422  0.935945       1
9   1.267248  0.173634 -1.223255       1
15 -0.045438  1.040886 -0.094035       1
3   1.772258 -0.347459  0.670140       1

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [9]:
df.head()

feature1  feature2  feature3  target
2  -0.449148 -1.556529 -1.674155       1
14  0.253623  0.739448 -0.096499       1
14  0.253623  0.739448 -0.096499       1
11  1.633728 -0.682544 -0.863484       1
12 -2.356102  0.347182  0.758053       1

In [10]:
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[ 1.02564103  0.19874576 -0.28147286]
 [ 0.19874576  1.02564103  0.10675198]
 [-0.28147286  0.10675198  1.02564103]]


In [11]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [12]:

eigen_values

array([0.6256614 , 1.32630385, 1.12495783])

In [13]:
eigen_vectors

array([[-0.65172443,  0.74834128,  0.12345283],
       [ 0.48046517,  0.28140349,  0.8306415 ],
       [-0.58686326, -0.60066414,  0.54294945]])

In [26]:
%pylab inline
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d import proj3d
from matplotlib.patches import FancyArrowPatch
class Arrow3D(FancyArrowPatch):
  def __init__(self, xs, ys, zs, *args, **kwargs):
    FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
    self._verts3d = xs, ys, zs
    def draw(self, renderer):
      xs3d, ys3d, zs3d = self._verts3d
      xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
      self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
      FancyArrowPatch.draw(self, renderer)
      fig = plt.figure(figsize=(7,7))
      ax = fig.add_subplot(111, projection='3d')
      ax.plot(df['feature1'], df['feature2'], df['feature3'], 'o', markersize=8, color='blue', alpha=0.2)
      ax.plot([df['feature1'].mean()], [df['feature2'].mean()], [df['feature3'].mean()], 'o', markersize=10, color='red', alpha=0.5)
      for v in eigen_vectors.T: a = Arrow3D([df['feature1'].mean(), v[0]], [df['feature2'].mean(), v[1]], [df['feature3'].mean(), v[2]], mutation_scale=20, lw=3, arrowstyle="-|>", color="r")
      ax.add_artist(a)
      ax.set_xlabel('x_values')
      ax.set_ylabel('y_values')
      ax.set_zlabel('z_values')
      plt.title('Eigenvectors')
      plt.show()

Populating the interactive namespace from numpy and matplotlib


In [17]:
pc = eigen_vectors[0:2]
pc

array([[-0.65172443,  0.74834128,  0.12345283],
       [ 0.48046517,  0.28140349,  0.8306415 ]])

In [18]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)

In [19]:
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

PC1       PC2  target
0 -1.078773 -2.044435       1
1  0.376154  0.249784       1
2  0.376154  0.249784       1
3 -1.682116 -0.124367       1
4  1.888923 -0.404657       1

In [23]:
import plotly.express as px

In [24]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'], y=new_df['PC2'], color=new_df['target'], color_discrete_sequence=px.colors.qualitative.G10 )
fig.update_traces(marker=dict(size=12, line=dict(width=2, color='DarkSlateGrey')), selector=dict(mode='markers'))
fig.show()